#!perl

use Test::More;
use Test::Pod::Coverage;
plan skip_all => "Test::Pod::Coverage 1.04 required for testing POD coverage" if $@;

# Test all modules that are not autogenerated by DBIx
my @pods = all_modules('modules');
for my $module (@pods) {
  next if $module =~ /RNAseqDB::Schema/;
  pod_coverage_ok($module);
}
done_testing();
